theme: jekyll-theme-slate
# theme: minima
# title: Changed the page
# author: Zain
# email: zain.9496@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
  # Changed the description of the document.
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  zainkhan-afk # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage